apiVersion: v1
kind: Service
metadata:
  name: {{ template "consul.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | trim | nindent 4 }}
    {{- end }}
    run: {{ .Release.Name }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - name: http
      port: 8500
  selector:
    run: {{ .Release.Name }}
