apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "raccoon.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels: {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
data:
  {{- toYaml .Values.raccoon.config | nindent 2 }}
