{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "siren.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "siren.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- range $key, $value := .Values.ingress.labels }}
{{ $key }}: {{ $value | quote | indent 4}}      #TODO: merge root labels
    {{- end }}
    run: {{ .Release.Name }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
{{- end -}}
