apiVersion: v1
kind: Secret
metadata:
  name: {{ template "siren.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.labels }}
{{ toYaml .Values.labels | trim | indent 4 }}
    {{- end }}
type: Opaque
data:
  DB_HOST: {{ .Values.database.host | b64enc | quote }}
  DB_NAME: {{ .Values.database.name | b64enc | quote }}
  DB_USER: {{ .Values.database.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  DB_PORT: {{ .Values.database.port | toString | b64enc | quote }}
